# Generated by Django 6.0.4 on 2026-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_engine', '0002_twinsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='favorite_color',
            field=models.CharField(default='Blue', help_text='Your favorite color for UI themes', max_length=50),
        ),
    ]
