# Generated by Django 6.0.4 on 2026-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_engine', '0003_userpreference_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='twinsettings',
            name='last_mood',
            field=models.CharField(default='Happy', help_text='Current emotional state for mood-aware responses', max_length=50),
        ),
    ]
